# @format

url: "https://johnathan.org"
permalink: simple
template_engine: liquid
timezone: America/Los_Angeles

collections:
  pages:
    permalink: /:slug/
  posts:
    permalink: /:slug/

cloudinary:
  transformations:
    standard: w_640,c_fill,q_90,dpr_2.0

pagination:
  enabled: true
