# This file is used by Rack-based servers during the Bridgetown boot process.

require "bridgetown-core/rack/boot"
require 'rack/rewrite'

use Rack::Rewrite do
  

  
  if ENV['BRIDGETOWN_ENV'] == "production" && ENV['HOST_ENV'] == "heroku"
    # Redirect from www to non-www
    r301 %r{.*}, 'https://johnathan.org$&', :if => Proc.new {|rack_env|
      rack_env['SERVER_NAME'] != 'johnathan.org'
    }

    # Redirect http to https when in production and using the Heroku-hosted app
    r301 %r{.*}, 'https://jdotorg.herokuapp.com$&', :scheme => 'http'
  end

  # /2020/12/file-name.html => /file-name/
  r301 %r{/\d{4}/\d{2}/(.*).html}, '/$1/'

  # /2020/12/file-name/ => /file-name/
  r301 %r{/\d{4}/\d{2}/(.*)/}, '/$1/'

  # /2020/12/file-name => /file-name/
  r301 %r{/\d{4}/\d{2}/(.*)}, '/$1/'

  ## Custom redirects to clean up references in old locations on the Internet
  r301 %r{/contact[/]?}, '/about/'
  r301 %r{/colophon[/]?}, '/about/'
  r301 %r{/stream-rtmp[/]?}, '/attempting-to-stream-a-webcam-to-an-rtmp-server/'
  r301 %r{/rtmp-nginx-apt[/]?}, '/add-rtmp-support-to-nginx-installed-from-apt/'
  r301 %r{/site-archives.*}, '/'
  r301 %r{/tag.*}, '/'
  r301 %r{/author.*}, '/about/'
  r301 %r{/rss.*}, '/feed.xml'
  r301 %r{/feed?cat=-434}, '/feed.xml'

  ## Redirecting from old post slug to new format
  r301 %r{^/the-canonical-spicy-chicken-sandwich/}, '/lists/the-canonical-spicy-chicken-sandwich/'
r301 %r{^/working-remotely/}, '/productivity/working-remotely/'
r301 %r{^/configure-a-raspberry-pi-as-a-print-server-for-dymo-label-printers/}, '/technology/configure-a-raspberry-pi-as-a-print-server-for-dymo-label-printers/'
r301 %r{^/cloudflare-argo-228-days-later/}, '/technology/cloudflare-argo-228-days-later/'
r301 %r{^/busting-cloudflare-cache-when-posting-to-wordpress-via-xml-rpc/}, '/technology/busting-cloudflare-cache-when-posting-to-wordpress-via-xml-rpc/'
r301 %r{^/not-voting-doubles-the-value-of-someone-elses-vote/}, '/journal/not-voting-doubles-the-value-of-someone-elses-vote/'
r301 %r{^/college-and-the-fear-of-change/}, '/learning/college-and-the-fear-of-change/'
r301 %r{^/the-four-part-solution-to-our-social-network-problem/}, '/journal/the-four-part-solution-to-our-social-network-problem/'
r301 %r{^/powerport-mini-the-charging-device-apple-should-have-made/}, '/technology/powerport-mini-the-charging-device-apple-should-have-made/'
r301 %r{^/deploying-a-jekyll-static-site-with-circle-ci/}, '/programming/deploying-a-jekyll-static-site-with-circle-ci/'
r301 %r{^/a-week-of-cloudflare-argo/}, '/technology/a-week-of-cloudflare-argo/'
r301 %r{^/lazy-loading-retina-images-in-a-jekyll-site/}, '/programming/lazy-loading-retina-images-in-a-jekyll-site/'
r301 %r{^/easy-redirect-links-within-jekyll/}, '/programming/easy-redirect-links-within-jekyll/'
r301 %r{^/an-auto-deploying-static-site-with-backend/}, '/programming/an-auto-deploying-static-site-with-backend/'
r301 %r{^/forcing-https-is-good-or-is-it-bad/}, '/programming/forcing-https-is-good-or-is-it-bad/'
r301 %r{^/where-work-happens/}, '/productivity/where-work-happens/'
r301 %r{^/remote-work/}, '/productivity/remote-work/'
r301 %r{^/linode-vs-digital-ocean-a-three-round-vps-benchmark-showdown/}, '/technology/linode-vs-digital-ocean-a-three-round-vps-benchmark-showdown/'
r301 %r{^/comparing-performance-of-multiple-apple-devices-before-and-after-spectre-security-update/}, '/technology/comparing-performance-of-multiple-apple-devices-before-and-after-spectre-security-update/'
r301 %r{^/on-developing-a-wordpress-theme/}, '/programming/on-developing-a-wordpress-theme/'
r301 %r{^/goals-for-2018/}, '/journal/goals-for-2018/'
r301 %r{^/status-available/}, '/journal/status-available/'
r301 %r{^/doubling-down-on-dns-records/}, '/programming/doubling-down-on-dns-records/'
r301 %r{^/on-moving-to-johnathan-org/}, '/johnathan.org/on-moving-to-johnathan-org/'
r301 %r{^/fixing-browsersync-not-reloading/}, '/programming/fixing-browsersync-not-reloading/'
r301 %r{^/canonical-reasons-for-pineapple-on-pizza/}, '/lists/canonical-reasons-for-pineapple-on-pizza/'
r301 %r{^/jpegmini/}, '/software/jpegmini/'
r301 %r{^/anker-roav-dash-cam-review/}, '/technology/anker-roav-dash-cam-review/'
r301 %r{^/new-workspace-a-story/}, '/productivity/new-workspace-a-story/'
r301 %r{^/do-you-know-why-youre-suffering/}, '/books/do-you-know-why-youre-suffering/'
r301 %r{^/special-snowflakes/}, '/journal/special-snowflakes/'
r301 %r{^/emotional-decisions/}, '/journal/emotional-decisions/'
r301 %r{^/a-simple-coffee-shop-musing/}, '/journal/a-simple-coffee-shop-musing/'
r301 %r{^/happiness-is-a-problem/}, '/journal/happiness-is-a-problem/'
r301 %r{^/how-hard-are-you-trying/}, '/books/how-hard-are-you-trying/'
r301 %r{^/my-learn-ruby-on-rails-list/}, '/programming/my-learn-ruby-on-rails-list/'
r301 %r{^/live-streaming-with-hardware-acceleration-using-a-raspberry-pi-and-rtmp-hls/}, '/programming/live-streaming-with-hardware-acceleration-using-a-raspberry-pi-and-rtmp-hls/'
r301 %r{^/add-rtmp-support-to-nginx-installed-from-apt/}, '/programming/add-rtmp-support-to-nginx-installed-from-apt/'
r301 %r{^/attempting-to-stream-a-webcam-to-an-rtmp-server/}, '/programming/attempting-to-stream-a-webcam-to-an-rtmp-server/'
r301 %r{^/fighting-ffmpeg/}, '/programming/fighting-ffmpeg/'
r301 %r{^/constantly-improving/}, '/books/constantly-improving/'
r301 %r{^/internet-arguments-even-garbage-fires-can-be-extinguished/}, '/journal/internet-arguments-even-garbage-fires-can-be-extinguished/'
r301 %r{^/on-going-back-to-regular-books/}, '/books/on-going-back-to-regular-books/'
r301 %r{^/fitbit-you-frustrate-me/}, '/technology/fitbit-you-frustrate-me/'
r301 %r{^/testing-out-a-new-temporary-markdown-editor/}, '/software/testing-out-a-new-temporary-markdown-editor/'
r301 %r{^/harder-than-it-should-be-jekyll-word-count/}, '/programming/harder-than-it-should-be-jekyll-word-count/'
r301 %r{^/my-overloaded-server-story/}, '/programming/my-overloaded-server-story/'
r301 %r{^/how-i-made-jekyll-post-generation-just-a-touch-easier/}, '/programming/how-i-made-jekyll-post-generation-just-a-touch-easier/'
r301 %r{^/starting-soon-bloc-io/}, '/learning/starting-soon-bloc-io/'
r301 %r{^/how-to-fix-misspelled-column-names-in-a-ruby-on-rails-database/}, '/programming/how-to-fix-misspelled-column-names-in-a-ruby-on-rails-database/'
r301 %r{^/future-ruby-on-rails-developer/}, '/learning/future-ruby-on-rails-developer/'
r301 %r{^/on-never-quitting/}, '/writing/on-never-quitting/'
r301 %r{^/become-a-genius/}, '/learning/become-a-genius/'
r301 %r{^/enemies-considered/}, '/journal/enemies-considered/'
r301 %r{^/re-invent-high-school/}, '/journal/re-invent-high-school/'
r301 %r{^/starting-ruby-on-rails/}, '/programming/starting-ruby-on-rails/'
r301 %r{^/replacing-my-four-year-old-macbook-pro/}, '/technology/replacing-my-four-year-old-macbook-pro/'
r301 %r{^/the-cold-brew-coffee-adventure/}, '/journal/the-cold-brew-coffee-adventure/'
r301 %r{^/lies-for-money/}, '/journal/lies-for-money/'
r301 %r{^/conquering-the-dev-career/}, '/journal/conquering-the-dev-career/'
r301 %r{^/my-first-legitimate-vagrantfile/}, '/programming/my-first-legitimate-vagrantfile/'
r301 %r{^/focusing-on-the-future-part-1/}, '/journal/focusing-on-the-future-part-1/'
r301 %r{^/48-hours-of-slack/}, '/technology/48-hours-of-slack/'
r301 %r{^/creativity/}, '/journal/creativity/'
r301 %r{^/incapacity/}, '/journal/incapacity/'
r301 %r{^/keeping-score/}, '/journal/keeping-score/'
r301 %r{^/the-cost-of-cutting-the-cord/}, '/technology/the-cost-of-cutting-the-cord/'
r301 %r{^/time-for-a-reset/}, '/journal/time-for-a-reset/'
r301 %r{^/beginners-mind/}, '/journal/beginners-mind/'
r301 %r{^/forget-your-goals/}, '/journal/forget-your-goals/'
r301 %r{^/morning-email-check-in-without-checking-out/}, '/journal/morning-email-check-in-without-checking-out/'
r301 %r{^/choosing-your-words/}, '/journal/choosing-your-words/'
r301 %r{^/18-resources-for-getting-started-with-wordpress/}, '/wordpress/18-resources-for-getting-started-with-wordpress/'
r301 %r{^/like-that-zappos-guy/}, '/books/like-that-zappos-guy/'
r301 %r{^/killing-it-in-people-relations/}, '/developer support/killing-it-in-people-relations/'
r301 %r{^/ten-days-a-californian/}, '/journal/ten-days-a-californian/'
r301 %r{^/endgame/}, '/journal/endgame/'
r301 %r{^/stress/}, '/journal/stress/'
r301 %r{^/why-this-site/}, '/johnathan.org/why-this-site/'
r301 %r{^/swifty/}, '/journal/swifty/'
r301 %r{^/iphone-trade-in/}, '/technology/iphone-trade-in/'
r301 %r{^/commuting-and-wasted-time/}, '/journal/commuting-and-wasted-time/'
r301 %r{^/magic/}, '/books/magic/'
r301 %r{^/blocks/}, '/writing/blocks/'
r301 %r{^/open-source-sagetv/}, '/television/open-source-sagetv/'
r301 %r{^/triple-digits-on-earth/}, '/journal/triple-digits-on-earth/'
r301 %r{^/forty-years/}, '/journal/forty-years/'
r301 %r{^/devops/}, '/journal/devops/'
r301 %r{^/remotely-working/}, '/journal/remotely-working/'
r301 %r{^/write-what-you-know/}, '/writing/write-what-you-know/'
r301 %r{^/failure-part-3/}, '/journal/failure-part-3/'
r301 %r{^/girl-code/}, '/programming/girl-code/'
r301 %r{^/using-words/}, '/journal/using-words/'
r301 %r{^/freebies/}, '/internet/freebies/'
r301 %r{^/recovering-from-failure-part-2/}, '/journal/recovering-from-failure-part-2/'
r301 %r{^/useful-mac/}, '/software/useful-mac/'
r301 %r{^/always-find-time/}, '/writing/always-find-time/'
r301 %r{^/alone/}, '/books/alone/'
r301 %r{^/tomorrow/}, '/books/tomorrow/'
r301 %r{^/self-comparison/}, '/books/self-comparison/'
r301 %r{^/do-or-die/}, '/books/do-or-die/'
r301 %r{^/putting-in-the-effort-to-become-a-professional-life-liver/}, '/books/putting-in-the-effort-to-become-a-professional-life-liver/'
r301 %r{^/fake-ssl-another-reason-to-own-a-mac/}, '/programming/fake-ssl-another-reason-to-own-a-mac/'
r301 %r{^/another-new-book/}, '/books/another-new-book/'
r301 %r{^/turning-pro/}, '/books/turning-pro/'
r301 %r{^/creativity/}, '/journal/creativity/'
r301 %r{^/crashplan/}, '/software/crashplan/'
r301 %r{^/after-40-days-of-writing/}, '/writing/after-40-days-of-writing/'
r301 %r{^/computer-on-the-bus/}, '/journal/computer-on-the-bus/'
r301 %r{^/thinking-about-old-posts/}, '/writing/thinking-about-old-posts/'
r301 %r{^/as-you-think/}, '/journal/as-you-think/'
r301 %r{^/apple-world-today/}, '/apple/apple-world-today/'
r301 %r{^/the-best-way-i-make-life-changes/}, '/journal/the-best-way-i-make-life-changes/'
r301 %r{^/financial-planning-and-investment-apps-that-dont-suck/}, '/software/financial-planning-and-investment-apps-that-dont-suck/'
r301 %r{^/through-an-open-window/}, '/journal/through-an-open-window/'
r301 %r{^/music/}, '/journal/music/'
r301 %r{^/telling-peoples-stories/}, '/journal/telling-peoples-stories/'
r301 %r{^/killing-your-friends-when-they-think-youre-not-looking/}, '/apple/killing-your-friends-when-they-think-youre-not-looking/'
r301 %r{^/a-first/}, '/writing/a-first/'
r301 %r{^/magic-room/}, '/writing/magic-room/'
r301 %r{^/to-write-you-must-read/}, '/writing/to-write-you-must-read/'
r301 %r{^/harrys-get-a-good-shave-without-nicking-your-wallet/}, '/reviews/harrys-get-a-good-shave-without-nicking-your-wallet/'
r301 %r{^/how-i-solved-related-posts-not-showing-when-running-wordpress-jetpack-and-nginx/}, '/wordpress/how-i-solved-related-posts-not-showing-when-running-wordpress-jetpack-and-nginx/'
r301 %r{^/learn-to-code-as-early-as-you-can/}, '/programming/learn-to-code-as-early-as-you-can/'
r301 %r{^/if-i-could-change-just-one-thing/}, '/journal/if-i-could-change-just-one-thing/'
r301 %r{^/vivaldi-a-new-browser-for-our-friends/}, '/software/vivaldi-a-new-browser-for-our-friends/'
r301 %r{^/favorite-thing-to-this-day/}, '/journal/favorite-thing-to-this-day/'
r301 %r{^/the-workforce-in-2030/}, '/journal/the-workforce-in-2030/'
r301 %r{^/on-the-bus-in-the-fog-unlike-a-dog-on-a-log-in-a-bog-with-nog/}, '/journal/on-the-bus-in-the-fog-unlike-a-dog-on-a-log-in-a-bog-with-nog/'
r301 %r{^/taking-notes/}, '/journal/taking-notes/'
r301 %r{^/positioning-for-the-journey-to-dreamland/}, '/journal/positioning-for-the-journey-to-dreamland/'
r301 %r{^/hunting-the-hunter-trying-to-take-a-photo-of-my-cat/}, '/cats/hunting-the-hunter-trying-to-take-a-photo-of-my-cat/'
r301 %r{^/never-gonna-give-you-up-never-gonna-put-you-down-sometimes/}, '/journal/never-gonna-give-you-up-never-gonna-put-you-down-sometimes/'
r301 %r{^/how-to-set-up-automatic-wordpress-blog-post-scheduling-with-ift-tt-and-buffer/}, '/automation/how-to-set-up-automatic-wordpress-blog-post-scheduling-with-ift-tt-and-buffer/'
r301 %r{^/ghostly-sharing-to-twitter-from-jetpacks-publicize-plugin/}, '/wordpress/ghostly-sharing-to-twitter-from-jetpacks-publicize-plugin/'
r301 %r{^/there-are-some-things-money-cant-buy-for-everything-else-theres-a-cat-in-a-box/}, '/cats/there-are-some-things-money-cant-buy-for-everything-else-theres-a-cat-in-a-box/'
r301 %r{^/extending-my-writing-goals-to-photography/}, '/photography/extending-my-writing-goals-to-photography/'
r301 %r{^/my-first-smartphone/}, '/journal/my-first-smartphone/'
r301 %r{^/running-out-of-coffee-creamer/}, '/journal/running-out-of-coffee-creamer/'
r301 %r{^/being-s-m-a-r-t-about-blogging-goals-for-the-new-year/}, '/journal/being-s-m-a-r-t-about-blogging-goals-for-the-new-year/'
r301 %r{^/analytics/}, '/journal/analytics/'
r301 %r{^/new-about-page/}, '/johnathan.org/new-about-page/'
r301 %r{^/finding-a-short-domain-based-on-a-name-is-harder-than-ever/}, '/johnathan.org/finding-a-short-domain-based-on-a-name-is-harder-than-ever/'
r301 %r{^/half-way-there/}, '/johnathan.org/half-way-there/'
r301 %r{^/the-space-in-which-i-craft/}, '/productivity/the-space-in-which-i-craft/'
r301 %r{^/why-i-write/}, '/journal/why-i-write/'
r301 %r{^/you-really-just-would-not-understand/}, '/journal/you-really-just-would-not-understand/'
r301 %r{^/poor-planning-on-your-part-does-not-necessarily-constitute-an-emergency-on-mine/}, '/journal/poor-planning-on-your-part-does-not-necessarily-constitute-an-emergency-on-mine/'
r301 %r{^/disabling-comments-on-existing-posts-after-disabling-comments-site-wide-with-wordpress/}, '/wordpress/disabling-comments-on-existing-posts-after-disabling-comments-site-wide-with-wordpress/'
r301 %r{^/create-a-photograph/}, '/photography/create-a-photograph/'
end

Bridgetown::Rack.boot

run RodaApp.freeze.app # see server/roda_app.rb