{
 "title": "ADS-B (dump1090-fa)",
 "description": "This dashboard displays dump1090 metrics that get exposed to Prometheus by the dump1090exporter.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Aircraft",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dump1090_recent_aircraft_observed{job=\"dump1090\", time_period=\"latest\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "max_over_time(dump1090_recent_aircraft_observed{job=\"dump1090\", time_period=\"latest\"}[30d:])",
     "legendFormat": "30d Peak"
    },
    {
     "expr": "dump1090_recent_aircraft_with_position{job=\"dump1090\", time_period=\"latest\"}",
     "legendFormat": "w/ Position"
    },
    {
     "expr": "dump1090_recent_aircraft_observed{job=\"dump1090\", time_period=\"latest\"} - dump1090_recent_aircraft_with_position{job=\"dump1090\", time_period=\"latest\"}",
     "legendFormat": "w/o Position"
    },
    {
     "expr": "dump1090_recent_aircraft_with_multilateration{job=\"dump1090\", time_period=\"latest\"}",
     "legendFormat": "MLAT"
    }
   ]
  },
  {
   "title": "Aircraft w/ Position",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "dump1090_recent_aircraft_with_position{job=\"dump1090\", time_period=\"latest\"}"
    }
   ]
  },
  {
   "title": "Max Range",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lengthmi" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "dump1090_recent_aircraft_max_range{job=\"dump1090\"} * 3.28084 / 5280"
    }
   ]
  },
  {
   "title": "Max Range (1y)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lengthmi" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time((dump1090_recent_aircraft_max_range{job=\"dump1090\"} * 3.28084 / 5280)[365d:])",
     "legendFormat": "1 Day"
    }
   ]
  },
  {
   "title": "Messages/Sec",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(dump1090_messages_total{job=\"dump1090\", time_period=\"latest\"}[1m])"
    }
   ]
  },
  {
   "title": "Aircraft Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "dump1090_recent_aircraft_observed{job=\"dump1090\", time_period=\"latest\"}"
    }
   ]
  },
  {
   "title": "Messages Last Hour",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(dump1090_messages_total{job=\"dump1090\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Strong Signal %",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dump1090_stats_local_strong_signals{time_period=\"last1min\"} / dump1090_stats_messages_total{time_period=\"last1min\"}"
    }
   ]
  },
  {
   "title": "Signal Peak",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "dump1090_stats_local_peak_signal_strength_dbFS{job=\"dump1090\", time_period=\"last1min\"}"
    }
   ]
  },
  {
   "title": "Maximum Range",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "lengthmi" } },
   "targets": [
    {
     "expr": "dump1090_recent_aircraft_max_range{job=\"dump1090\"} * 3.28084 / 5280",
     "legendFormat": "Current"
    },
    {
     "expr": "max_over_time((dump1090_recent_aircraft_max_range{job=\"dump1090\"} * 3.28084 / 5280)[30d:])\n",
     "legendFormat": "30d Peak"
    }
   ]
  },
  {
   "title": "Average Range",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "lengthmi" } },
   "targets": [
    {
     "expr": "avg_over_time(dump1090_recent_aircraft_max_range{job=\"dump1090\", time_period=\"latest\"}[1m]) * 3.28084 / 5280\n",
     "legendFormat": "1 Minute"
    },
    {
     "expr": "avg_over_time(dump1090_recent_aircraft_max_range{job=\"dump1090\", time_period=\"latest\"}[1h])\n * 3.28084 / 5280",
     "legendFormat": "1 Hour"
    },
    {
     "expr": "avg_over_time(dump1090_recent_aircraft_max_range{job=\"dump1090\", time_period=\"latest\"}[12h]) * 3.28084 / 5280\n",
     "legendFormat": "12 Hours"
    },
    {
     "expr": "avg_over_time(dump1090_recent_aircraft_max_range{job=\"dump1090\", time_period=\"latest\"}[1d]) * 3.28084 / 5280\n",
     "legendFormat": "1 Day"
    }
   ]
  },
  {
   "title": "messages / sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(dump1090_messages_total{job=\"dump1090\", time_period=\"latest\"}[1m])",
     "legendFormat": "latest"
    },
    {
     "expr": "max_over_time(rate(dump1090_messages_total{job=\"dump1090\", time_period=\"latest\"}[1m])[30d:])",
     "legendFormat": "30D Peak"
    }
   ]
  },
  {
   "title": "Tracks Created",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dump1090_stats_tracks_all{job=\"dump1090\", time_period=\"last1min\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Signal Strength",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dump1090_stats_local_signal_strength_dbFS{job=\"dump1090\", time_period=\"last1min\"}",
     "legendFormat": "mean"
    },
    {
     "expr": "dump1090_stats_local_peak_signal_strength_dbFS{job=\"dump1090\", time_period=\"last1min\"}",
     "legendFormat": "peak"
    },
    {
     "expr": "dump1090_stats_local_noise_level_dbFS{job=\"dump1090\", time_period=\"last1min\"}",
     "legendFormat": "noise"
    }
   ]
  },
  {
   "title": "Strong Signal %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "dump1090_stats_local_strong_signals / dump1090_stats_messages_total",
     "legendFormat": "Last 1 Minute"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "dump1090_stats_cpu_demod_milliseconds{job=\"dump1090\", time_period=\"last1min\"}",
     "legendFormat": "demod"
    },
    {
     "expr": "dump1090_stats_cpu_reader_milliseconds{job=\"dump1090\", time_period=\"last1min\"}",
     "legendFormat": "usb"
    },
    {
     "expr": "dump1090_stats_cpu_background_milliseconds{job=\"dump1090\", time_period=\"last1min\"}",
     "legendFormat": "other"
    }
   ]
  },
  {
   "title": "Positions Skipped",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dump1090_stats_cpr_local_skipped{time_period=\"last1min\"}",
     "legendFormat": "Local"
    },
    {
     "expr": "dump1090_stats_cpr_global_skipped{time_period=\"last1min\"}",
     "legendFormat": "Global"
    }
   ]
  }
 ]
}