{
 "title": "Ecowitt Weather",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Current Temperature",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "temp_f", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Humidity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "humidity_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Rain Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "in/hr" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rainrate_in", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Barometer",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "inHg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "baromrel_mbar", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Wind Speed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "windspeed_mph", "legendFormat": "Current Speed" },
    { "expr": "windgust_mph", "legendFormat": "Gust" }
   ]
  },
  {
   "title": "Temperature Change (1h)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "temp_f - temp_f offset 1h", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Rain (day)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "lengthin" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "dailyrain_in", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Rain (week)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "lengthin" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "weeklyrain_in", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Rain (month)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "lengthin" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "monthlyrain_in", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Wind Speed (maxes)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(windgust_mph[1d])",
     "legendFormat": "Last 1d"
    },
    {
     "expr": "max_over_time(windgust_mph[30d])",
     "legendFormat": "Last 30d"
    }
   ]
  },
  {
   "title": "Current Temperature",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "expr": "(\n  (temp_f > bool 80 or humidity_percent >= bool 40)\n  * \n  (\n    -42.379\n    + 2.04901523 * temp_f\n    + 10.14333127 * humidity_percent\n    - 0.22475541 * temp_f * humidity_percent\n    - 0.00683783 * temp_f^2\n    - 0.05481717 * humidity_percent^2\n    + 0.00122874 * temp_f^2 * humidity_percent\n    + 0.00085282 * temp_f * humidity_percent^2\n    - 0.00000199 * temp_f^2 * humidity_percent^2\n  )\n) + (temp_f <= bool 80 and humidity_percent < bool 40) * temp_f\n",
     "legendFormat": "Heat Index"
    },
    {
     "expr": "temp_f - ((100 - humidity_percent)/5)",
     "legendFormat": "Dew Point"
    },
    {
     "expr": "( (windspeed_mph{} > bool 1.63) * (35.74 + (0.6215 * temp_f{}) - (35.75 * (windspeed_mph{}^0.16)) + (0.4275 * temp_f{} * (windspeed_mph{}^0.16))) )\n+ ignoring (windspeed_mph) ( (windspeed_mph{} <= bool 1.63) * temp_f{} )\n",
     "legendFormat": "Wind Chill"
    },
    { "expr": "temp_f{}", "legendFormat": "Temperature" }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    { "expr": "humidity_percent", "legendFormat": "Humidity %" }
   ]
  },
  {
   "title": "Barometer",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "targets": [
    { "expr": "baromrel_mbar", "legendFormat": "Pressure (inHg)" }
   ]
  },
  {
   "title": "Wind Direction",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "winddir_degree", "legendFormat": "__auto" }
   ]
  }
 ]
}