on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/flat.yml
  workflow_dispatch: null
  schedule:
    - cron: 0 0 * * *
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.10.x
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch data (Raindrop - On The Web)
        uses: githubocto/flat@v3
        with:
          http_url: https://api.raindrop.io/rest/v1/raindrops/22861167
          downloaded_filename: src/_data/raindrop/on_the_web.json
          authorization: Bearer ${{ secrets.RAINDROP_KEY }}
      - name: Fetch data (Raindrop - Apps and Software)
        uses: githubocto/flat@v3
        with:
          http_url: https://api.raindrop.io/rest/v1/raindrops/22861155
          downloaded_filename: src/_data/raindrop/apps_and_software.json
          authorization: Bearer ${{ secrets.RAINDROP_KEY }}
      - name: Fetch data (Raindrop - Blogs)
        uses: githubocto/flat@v3
        with:
          http_url: https://api.raindrop.io/rest/v1/raindrops/22861059
          downloaded_filename: src/_data/raindrop/blogs.json
          authorization: Bearer ${{ secrets.RAINDROP_KEY }}
      - name: Fetch data (Raindrop - Podcasts)
        uses: githubocto/flat@v3
        with:
          http_url: https://api.raindrop.io/rest/v1/raindrops/22861052
          downloaded_filename: src/_data/raindrop/podcasts.json
          authorization: Bearer ${{ secrets.RAINDROP_KEY }}
      - name: Fetch data (Raindrop - Books)
        uses: githubocto/flat@v3
        with:
          http_url: https://api.raindrop.io/rest/v1/raindrops/22861019
          downloaded_filename: src/_data/raindrop/books.json
          authorization: Bearer ${{ secrets.RAINDROP_KEY }}
      - name: Fetch data (Raindrop - Programming)
        uses: githubocto/flat@v3
        with:
          http_url: https://api.raindrop.io/rest/v1/raindrops/22861020
          downloaded_filename: src/_data/raindrop/programming.json
          authorization: Bearer ${{ secrets.RAINDROP_KEY }}
